// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lethal.core.persistence;

#nullable disable

namespace ShooterARPGProject.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260909033543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("StatDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRangePaired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PairedCounterpartId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatDefinitions");
                });

            modelBuilder.Entity("StatTagEntity", b =>
                {
                    b.Property<string>("StatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("StatId", "Tag");

                    b.ToTable("StatTagEntity");
                });

            modelBuilder.Entity("StatTagEntity", b =>
                {
                    b.HasOne("StatDefinitionEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StatDefinitionEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
