// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lethal.core.persistence;

#nullable disable

namespace ShooterARPGProject.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260910035116_AddCodeName")]
    partial class AddCodeName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterBaseStatEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("CharacterId", "StatId");

                    b.HasIndex("StatId");

                    b.ToTable("CharacterBaseStatEntity");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterStartingResourceEntity", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "StatId");

                    b.HasIndex("StatId");

                    b.ToTable("CharacterStartingResourceEntity");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.stats.StatDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRangePaired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PairedCounterpartId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatDefinitions");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.stats.StatTagEntity", b =>
                {
                    b.Property<string>("StatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("StatId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("StatTagEntity");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.stats.TagEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlayerVisible")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("TagEntity");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterBaseStatEntity", b =>
                {
                    b.HasOne("lethal.core.persistence.entities.characters.CharacterDefinitionEntity", null)
                        .WithMany("BaseStats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lethal.core.persistence.entities.stats.StatDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterStartingResourceEntity", b =>
                {
                    b.HasOne("lethal.core.persistence.entities.characters.CharacterDefinitionEntity", null)
                        .WithMany("StartingResources")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lethal.core.persistence.entities.stats.StatDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lethal.core.persistence.entities.stats.StatTagEntity", b =>
                {
                    b.HasOne("lethal.core.persistence.entities.stats.StatDefinitionEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lethal.core.persistence.entities.stats.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lethal.core.persistence.entities.characters.CharacterDefinitionEntity", b =>
                {
                    b.Navigation("BaseStats");

                    b.Navigation("StartingResources");
                });

            modelBuilder.Entity("lethal.core.persistence.entities.stats.StatDefinitionEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
