using Godot;
using System;
using System.IO;
using System.Linq;
using System.Text;
using lethal.core.persistence;

public partial class StatsClassGenerator : Node
{
    public override void _Ready()
    {
        using var db = new GameDbContext();
        var definitions = db.StatDefinitions.OrderBy(s => s.Id).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by StatsClassGenerator — do not edit by hand.");
        sb.AppendLine("// Regenerate after any change to StatDefinitions.");
        sb.AppendLine();
        sb.AppendLine("namespace lethal.core.persistence;");
        sb.AppendLine();
        sb.AppendLine("public static class Stats");
        sb.AppendLine("{");

        foreach (var def in definitions)
        {
            string identifier = SanitizeIdentifier(def.CodeName);
            sb.AppendLine($"    public static readonly StatId {identifier} = new(\"{def.Id}\");");
        }

        sb.AppendLine("}");

        string outputPath = ProjectSettings.GlobalizePath("res://core/persistence/Stats.cs");
        File.WriteAllText(outputPath, sb.ToString());

        GD.Print($"[StatsClassGenerator] Wrote {definitions.Count} stat constants to {outputPath}");
    }

    private static string SanitizeIdentifier(string raw)
    {
        var cleaned = new string(raw.Where(char.IsLetterOrDigit).ToArray());
        if (cleaned.Length == 0 || char.IsDigit(cleaned[0]))
        {
            cleaned = "_" + cleaned;
        }
        return cleaned;
    }
}