using Godot;
using System;
using System.IO;
using System.Linq;
using System.Text;
using lethal.core.persistence;
using lethal.core.persistence.entities.stats;

namespace lethal.core.tools;
public static partial class TagsClassGenerator
{
    public static void Generate()
    {
        using var db = new GameDbContext();
        var tags = db.Set<TagEntity>().OrderBy(t => t.Name).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by TagsClassGenerator — do not edit by hand.");
        sb.AppendLine();
        sb.AppendLine("using Godot;"); // Required for StringName namespace
        sb.AppendLine();
        sb.AppendLine("namespace lethal.core.persistence;");
        sb.AppendLine();
        sb.AppendLine("public static class Tags");
        sb.AppendLine("{");

        foreach (var tag in tags)
        {
            string identifier = SanitizeIdentifier(tag.CodeName);
            // StringName cannot be const, so we use static readonly
            sb.AppendLine($"    public static readonly StringName {identifier} = \"{tag.Name}\";");
        }

        sb.AppendLine("}");

        string outputPath = ProjectSettings.GlobalizePath("res://core/persistence/generated/Tags.cs");
        File.WriteAllText(outputPath, sb.ToString());

        GD.Print($"[TagsClassGenerator] Wrote {tags.Count} tag constants to {outputPath}");
    }

    private static string SanitizeIdentifier(string raw)
    {
        var cleaned = new string(raw.Where(char.IsLetterOrDigit).ToArray());
        if (cleaned.Length == 0 || char.IsDigit(cleaned[0]))
        {
            cleaned = "_" + cleaned;
        }
        return char.ToUpper(cleaned[0]) + cleaned.Substring(1);
    }
}